name: Run x.sh on Push

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: sinan-Aspire-A515-47
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run x.sh
        run: |
          chmod +x ~/gitartik/stmblink/fastblinktrio/x.sh
          ~/gitartik/stmblink/fastblinktrio/x.sh
