name: Run x.sh on Push

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on:
      - self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run x.sh
        run: |
          chmod +x ~/gitartik/stmblink/x.sh
          ~/gitartik/stmblink/x.sh
          sudo chown -R $USER:$USER /home/sinan/gitartik/stmblink/actions-runner/_work/stmblink

